10000-Bagger/free-topic-study

- new/testflight.md
- flutter로 ios 테스트 앱 배포하기 - TestFlight 
- flutter
- test flight
- ios
---
오늘 플러터로 만든 반디부디 앱을 테스트하기 위해 TestFlight로 배포한 경험에 대해 써보았습니다
_근데 이제 TIL로 변질된.._
iOS 처음 배포해보는데 
기록용으로도 쓸 겸 
혹시 다른분들도 관심이 있을수도 있지 않을까 해서
써봤습네다
> [1주차 3] flutter로 ios 테스트 앱 배포하기 - TestFlight 

- woo/webflux-debugging.md
- Reactor 디버깅 
- java
- reactor
- debugging
---
> [2주차 1] Reactor Debugging

- new/flutter.md
- 크로스 플랫폼 앱
- React Native
- Flutter
---
> [2주차 1] 크로스 플랫폼 앱

- hong/refactoring/making-highly-reusable-component.md
재사용성이 높은 컴포넌트 만들기
반디부디 frontend 기능 추가하면서 Clean Code에서 배운 내용을 적용해 보려고 고민한 부분을 정리했습니다.  
frontend refactoring, clean code, highly reusable components
---
> [2주차 5] 재사용성이 높은 컴포넌트 만들기

- woo/reactor-test.md
- Reactor Test
- reactor-test
- StepVerifier
- TestPublisher
- PublisherProbe
---
> [3주차 2] Reactor Test

- hong/nextjs/authentication.md
Authentication, Authorization, Session Management Using Next.js
최근에 도은이가 반디부디 auth 관련 부분 리팩토링 작업을 하길래 나중에 한번 봐야지 하고 안 본 Next.js의 Authentication 문서를 공부했습니다. 공부하면서 몰랐던 nextjs 기능이 많다는 걸을 느끼네요;;
Authentication, Authorization, Session Management, Middleware, Server Actions, Route Handlers, Data Access Layer, Cookie-based Sessions, Database Sessions
> [3주차 4] Authentication, Authorization, Session Management Using Next.js

- jin/MySQL 파티션 2 - 파티션의 종류.md
- jin/[DB] MySQL 파티션 2 - 파티션의 종류.md
파티션의 종류
Range Partition, List Partition, Hash Partition, Key Partition
---
> [4주차 4] MySQL 파티션 2 - 파티션의 종류.md

- jin/[Cache] 간단한 캐시 Read-Write 전략.md
> [6주차 1 미완] 간단한 캐시 Read-Write 전략.md

- jin/[Kotlin] 예외 처리 1 - Result 객체.md
- jin/[Kotlin] 코틀린과 Null.md
코틀린과 널, 예외 처리에 대하여
책 외의 다양한 좋은 자료들..
- [[에러 핸들링을 다른 클래스에게 위임하기 (Kotlin 100% 활용)]](https://toss.tech/article/kotlin-result)
- [[서킷브레이커 사용 방식 개선하기 | 당근 SERVER 밋업 2회]](https://www.youtube.com/watch?v=ThLfHtoEe1I)
- [[MSA 환경에서 네트워크 예외를 잘 다루는 방법]](https://tech.kakaopay.com/post/msa-transaction/)
---
> [8주차 1] 코틀린과 널, 예외 처리에 대하여

- jin/[Java] Concurrency 3 - Java 9 Flow 1.md
Java 9 Flow 1
리액티브 프로그래밍에 앞서 Flow에 대한 설명이 먼저 오는 것이 어색하지만, 리액티브 프로그래밍은 좀 더 자세히 공부해야 할 것 같아 Flow 부터..
뭔가 읽고 쓰는데는 오래 걸렸는데 지금 읽어보면 글이 매우 짧은 듯
> [8주차 2] Java 9 Flow.md

- jin/[Java] Java Concurrency 2 - 스레드와 CompletableFuture의 사용법.md
Java Concurrency 2 - 스레드와 CompletableFuture의 사용법.md
스레드, 스레드 풀, 하드웨어 스레드-자바 스레드, CompletableFuture, Exectuors
---
> [7주차 1] Java Concurrency 2 - 스레드와 CompletableFuture의 사용법.md

- hong/refactoring/making-clean-function.md
잘 읽히고, 깔끔한 함수 만들기
Clean Code의 3장 함수 편을 보고 난 뒤에 [지난번에 리팩토링한 반디부디의 `RHFTextField`](https://github.com/10000-Bagger/free-topic-study/pull/30)가 초라하고 부끄럽게 느껴졌습니다... 따라서 다시 한번 리팩토링한 과정을 정리했습니다~
Clean Code, Refactoring
---
> [4주차 3] RHFTextField에 Clean Code 적용하기 - 함수 편

- woo/set-concurrency.md
- ConcurrentKafkaListenerContainerFactory는 어떻게 Message 동시 처리를 가능하게 하는가?
- spring-kafka
- ConcurrentKafkaListenerContainerFactory
---
> [7주차 2] ConcurrentKafkaListenerContainerFactory는 어떻게 Message 동시 처리를 가능하게 하는가?

- jin/[Spring] Dispather Servlet.md
Dispather Servlet
Servlet, Dispather Servlet, Front Controller
---
> [10주차 2] Dispather Servlet

- jin/[Spring] AOP 사용시 주의사항.md
AOP 사용시 주의사항
Spring AOP, Proxy 패턴, 내부 호출 문제,  JDK Dynamic Proxy, CGLIB (Code Generate Library)
> [10주차 3] AOP 사용시 주의사항

- jin/[Spring] 간단한 Spring MVC 구조와 흐름.md
간단한 Spring MVC 구조와 흐름
Spring MVC, Front Controller, Dispatcher Servlet, HandlerMapping, ViewResolver
> [11주차 2] 간단한 Spring MVC 구조와 흐름.md

- jin/[Java] 자바 버전별 주요 변화 총정리 (~17).md
- jin/[Java] 자바 버전별 주요 변화 총정리.md
자바 버전별 주요 변화 총정리
- [11주차 3] Java 17 이전의 변화들
- [12주차 1] Sealed Class, 타입 추론 var, 중간 중간 소소한 변화들 추가
> [12주차 1 완] 자바 버전별 주요 변화 총정리

- jin/[Java] 자바 버전별 주요 변화 총정리 (~17).md
> docs : G1GC, Thread-Local Handshakes 추가

- woo/bucket4j.md
- Bucket4j
- rate-limiter
- bucket4j
---
> [10주차 2] Bucket4j

- woo/resilience4j-circuit-breaker.md
- Resilience4j - CircuitBreaker
- Resilience4j
- CircuitBreaker
---
> [11주차 1] Resilience4j - CircuitBreaker

- jin/[Java] GC 4편 - G1GC.md
> [12주차 2] GC 4편 - G1GC.md

- jin/[Java] NavigableMap으로 정렬된 맵을 탐험해보자.md
[13주차 1] NavigableMap으로 정렬된 맵을 탐험해보자.md
NavigableMap, lower_bound, uppder_bound Red-Black Tree
---
> [13주차 1] NavigableMap으로 정렬된 맵을 탐험해보자.md

- jin/[Java] ThreadPoolExecutor의 스레드 갯수는 어떻게 관리되는가.md
ThreadPoolExecutor의 스레드 갯수는 어떻게 관리되는가
ThreadPoolExecutor, corePoolSize, maximumPoolSize, keepAliveTime, Blocking Queue, RejectedExecutionHandler, ThreadPoolExecutor Hook, Lifecycle 등등..
> [16주차 1 - 완] ThreadPoolExecutor의 스레드 갯수는 어떻게 관리되는가

- woo/observer-pattern.md
- Observer Pattern
- design-pattern
- observer-pattern
---
> [16주차 1] Observer Pattern

- woo/singleton-pattern.md
- Singleton Pattern
- Design Pattern
- Singleton
---
> [17주차 3] Singleton Pattern

- hong/spring/스프링 핵심 원리 - 기본편/9. 빈 스코프.md
> [21주차 2] 9. 빈 스코프

- hong/flutter/코드팩도리의 플러터 프로그래밍/ch01.md
코드팩토리의 플러터 프로그래밍
- 00. 개발 환경 구축
- 01.  다트 언어 마스터하기
---
> [23주차 2] 코드팩토리의 플러터 프로그래밍: 개발 환경 구축, 다트 언어 마스터하기

- jin/Yorkie CI execution Time 줄이기.md
> [28주차 1] Yorkie CI execution Time 줄이기.md

- hong/machine-learning/Local LLM과 함께 일해보기.md
Local LLM에 RAG 적용하기
로컬에서 실행하는 LLM에 사내 자료로 튜닝하는 과정을 수행해보았습니다.
실제 결과는 좋지 못해서.. 조금 아쉽네요..ㅠㅡㅠ 하지만 덕분에 다양한 자료를 공부해서 관련 자료 남깁니다.
---
> [27주차 2] Local LLM에 RAG 적용하기

- hong/machine-learning/Local LLM과 함께 일해보기.md
Local LLM과 함께 일해보기
우아한테크코스에서 "로컬 LLM과 함께 일해보기" 발표를 보고 흥미로워서 개인적으로 실험해본 결과를 공유합니다.
---
> [27주차 1] Local LLM과 함께 일해보기

- jin/[Data Structure] Treap.md
> [30주차 1] Treap

- hong/java/jvm-performance-monitoring.md
JVM 성능 분석 및 모니터링 도구: jstat, jmap, jstack
이력서에 적은 내용 리뷰 하다가 잘 기억이 나지 않는 JVM 성능 분석 도구들에 대해 공부한 내용입니다.
---
> [10주차 1] JVM 성능 분석 및 모니터링 도구

- hong/python/effective-python/1. Pythonic Thinking.md
Effective Python. 1장: 파이썬답게 생각하기
파이썬 공부 중..
---
> [11주차 1] Effective Python. 1장: 파이썬답게 생각하기

- hong/spring/hong/spring/스프링 핵심 원리 - 기본편/2. 스프링 핵심 원리 이해 2 - 객체 지향 원리 적용.md
스프링 핵심 원리: 3. 스프링 핵심 원리 이해 2 - 객체 지향 원리 적용
---
> [13주차 3][14주차 1] 스프링 핵심 원리: 3. 스프링 핵심 원리 이해 2 - 객체 지향 원리 적용

- hong/spring/스프링 핵심 원리 - 기본편/4. 스프링 컨테이너와 스프링 빈.md
스프링 핵심 원리: 4. 스프링 컨테이너와 스프링 빈
---
> [14주차 2] 스프링 핵심 원리: 4. 스프링 컨테이너와 스프링 빈

- hong/spring/스프링 핵심 원리 - 기본편/6. 컴포넌트 스캔.md
> [15주차 2] 스프링 핵심 원리: 6. 컴포넌트 스캔

- hong/general/용어 정리.md
최근 습득한 키워드에 대한 공부한 내용을 정리했습니다.
kotest, querydsl, gRPC, squadcast, GPG Key, helm chart. npmrc, secure coding
---
> [16주차 1] 용어 정리

- hong/kotest/examples/상황에 따른 kotest 예제.md
상황에 따른 kotest 사용 예제를 공부했습니다.
---
> [16주차 2] 상황에 따른 kotest 예제

- hong/spring/스프링 핵심 원리 - 기본편/7. 의존관계 자동 주입.md
7. 의존관계 자동 주입
아.. 섹션 7 너무 내용이 많네요... 1회차 더 사용하겠숩니다..
---
> [17주차 2] 7. 의존관계 자동 주입 2

- hong/typescript/Typescript: enum, const enum, as const.md
Typescript: enum, const enum, as const
일을 하면서, enum, const enum, as const 중 하나를 선택해서 작업하던 중에 적합한 상황에 따라 구분해서 사용해야할 것 같아 공부했습니다.
---
> [19주차 1] Typescript: enum, const enum, as const

- hong/github-actions/Self-hosted Runner.md
GitHub Action: Self-hosted Runner
원래는 Github Actions 작업 파일 수정한 후 내부에서 테스트 해보는 방법을 찾았으나..
결국 다른 걸 공부하게 됐네여... 시간이 없어 실패작으로 올립니다..ㅠㅡㅠ
---
> [19주차 2] GitHub Action: Self-hosted Runner

- hong/spring/스프링 핵심 원리 - 기본편/8. 빈 생명주기 콜백.md
> [21주차 1] 8. 빈 생명주기 콜백

- hong/kotlin/Don’t hardcode Coroutine Dispatchers when creating new coroutines.md
…nes.md
Don’t hardcode Coroutine Dispatchers when creating new coroutines
---
> [22주차 1 미완] Don’t hardcode Coroutine Dispatchers when creating new coroutines

- hong/flutter/코드팩도리의 플러터 프로그래밍/ch03.md
코드팩토리의 플러터 프로그래밍: ch.03 다트 비동기 프로그래밍
---
> [25주차 1] Flutter Programming: ch.03 다트 비동기 프로그래밍

- hong/flutter/코드팩도리의 플러터 프로그래밍/ch05.md
Flutter Programming: ch05. 플러터 입문하기
---
> [26주차 1] Flutter Programming: ch05. 플러터 입문하기

- hong/kafka/kafka, AVRO & Schema Registry.md
Kafka, AVRO & Schema Registry
---
> [29주차 1] Kafka, AVRO & Schema Registry
